apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/flask-app

patches:
  - path: patch-kustomization.yaml
    target:
      kind: Kustomization

  - path: patch-gitrepository.yaml
    target:
      kind: GitRepository
